---
- name: Bring up docker containers
  hosts: all
  gather_facts: false
  vars:
    inventory:
      - name: k8s-master
        image: "chrismeyers/centos7"
      - name: k8s-minion
        image: "chrismeyers/centos7"

  roles:
    - { role: provision_docker,
        provision_docker_inventory: "{{ inventory }}",
        tags: provision_docker }

  tasks:
    - name: Group primary
      add_host:
        hostname: "{{ item }}"
        groups: k8s-master
      with_items:
        - k8s-master
      tags: provision_docker

    - name: Group secondaries
      add_host:
        hostname: "{{ item }}"
        groups: k8s-minion
      with_items:
        - k8s-minion
      tags: provision_docker


- name: Hello world
  hosts: docker_containers
  tasks:
    - debug: msg="Hello World"
    - debug: msg="System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

- name: variable precedence test
  hosts: all
  tasks:
    - shell: ip addr show
      register: result

    - debug: var=result

- name: Hello world
  hosts: k8s-master
  tasks:
    - debug: msg="Hello from master"

- name: Hello world
  hosts: k8s-minion
  tasks:
    - debug: msg="Hello from minion"
